GET http://localhost:3000/users HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Matheus",
    "email": "matheus@email.com"
}

###

GET http://localhost:3000/users/5dcfb083-652f-4e76-b42f-8530a9aa1f02 HTTP/1.1
content-type: application/json



